spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true